export const dummyInterviewChains = [
    {
      InterviewChainID: 1,
      ClientID: 101,
      EndClientName: "EndClientX",
      InterviewType: "Technical",
      InterviewDate: "2025-03-10",
      InterviewStartTime: "14:00",
      InterviewEndTime: "15:00",
      InterviewMethod: "Video Call",
      InterviewStatus: "Completed",
      InterviewSupport: "None required",
      Outcome: "Next Round",
      ParentInterviewChainID: null,
      CreatedDate: "2025-03-07",
      ModifiedDate: "2025-03-07",
    },
    {
      InterviewChainID: 2,
      ClientID: 101,
      EndClientName: "EndClientX",
      InterviewType: "HR",
      InterviewDate: "2025-03-11",
      InterviewStartTime: "15:00",
      InterviewEndTime: "16:00",
      InterviewMethod: "In-person",
      InterviewStatus: "Scheduled",
      InterviewSupport: "Technical Support",
      Outcome: null,
      ParentInterviewChainID: 1,
      CreatedDate: "2025-03-07",
      ModifiedDate: "2025-03-07",
    },
    // Simulate 10+ chains
    ...Array.from({ length: 10 }, (_, i) => ({
      InterviewChainID: i + 3,
      ClientID: 102 + i,
      EndClientName: `EndClient${i + 1}`,
      InterviewType: ["Initial Screening", "Technical"][i % 2],
      InterviewDate: `2025-03-1${i + 2}`,
      InterviewStartTime: "10:00",
      InterviewEndTime: "11:00",
      InterviewMethod: "Video Call",
      InterviewStatus: ["Scheduled", "Completed"][i % 2],
      InterviewSupport: "None required",
      Outcome: i % 3 === 0 ? "Next Round" : null,
      ParentInterviewChainID: i % 2 === 0 ? i + 2 : null,
      CreatedDate: "2025-03-07",
      ModifiedDate: "2025-03-07",
    })),
  ];