import type { Client } from "../types/client"
import type { Employee } from "../types/employee"
import type { SubscriptionPlan } from "../types/subscriptionPlan"
import type { PostPlacementPlan } from "../types/postPlacementPlan"

export const dummyClients: Client[] = [
  {
    ClientID: 1,
    ClientName: "John Doe",
    EnrollmentDate: "2023-01-15",
    TechStack: "React, Node.js",
    MarketingStartDate: "2023-02-01",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 123-4567",
    PersonalEmailAddress: "john.doe@example.com",
    MarketingEmailID: "john.doe.marketing@careervest.com",
    MarketingEmailPassword: "password123",
    AssignedRecruiterID: 1,
    VisaStatus: "H1B",
    LinkedInURL: "https://www.linkedin.com/in/johndoe",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_john_doe.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-01-15T10:00:00Z",
    UpdatedTS: "2023-02-01T14:30:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 1,
    PostPlacementPlanID: null,
    TotalDue: 5000,
    TotalPaid: 2500,
  },
  {
    ClientID: 2,
    ClientName: "Jane Smith",
    EnrollmentDate: "2023-02-01",
    TechStack: "Python, Django",
    MarketingStartDate: "2023-02-15",
    PlacedDate: "2023-04-01",
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 987-6543",
    PersonalEmailAddress: "jane.smith@example.com",
    MarketingEmailID: "jane.smith.marketing@careervest.com",
    MarketingEmailPassword: "password456",
    AssignedRecruiterID: 2,
    VisaStatus: "US Citizen",
    LinkedInURL: "https://www.linkedin.com/in/janesmith",
    MarketingEndDate: "2023-04-01",
    JobOutcome: "Placed",
    JobStartDate: "2023-04-15",
    JobSalary: 95000,
    PercentageFee: 15,
    ResumeBlobKey: "resume_jane_smith.pdf",
    ClientStatus: "Placed",
    CreatedTS: "2023-02-01T09:00:00Z",
    UpdatedTS: "2023-04-01T16:45:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Recruiter",
    SubscriptionPlanID: 2,
    PostPlacementPlanID: 1,
    TotalDue: 7500,
    TotalPaid: 7500,
  },
  {
    ClientID: 3,
    ClientName: "Bob Johnson",
    EnrollmentDate: "2023-03-01",
    TechStack: "Java, Spring",
    MarketingStartDate: "2023-03-15",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 246-8135",
    PersonalEmailAddress: "bob.johnson@example.com",
    MarketingEmailID: "bob.johnson.marketing@careervest.com",
    MarketingEmailPassword: "password789",
    AssignedRecruiterID: 1,
    VisaStatus: "Green Card",
    LinkedInURL: "https://www.linkedin.com/in/bobjohnson",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_bob_johnson.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-03-01T11:30:00Z",
    UpdatedTS: "2023-03-15T13:15:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 1,
    PostPlacementPlanID: null,
    TotalDue: 5000,
    TotalPaid: 1000,
  },
  {
    ClientID: 4,
    ClientName: "Alice Brown",
    EnrollmentDate: "2023-04-01",
    TechStack: "Angular, .NET",
    MarketingStartDate: "2023-04-15",
    PlacedDate: null,
    BackedOutDate: "2023-05-01",
    BackedOutReason: "Found job independently",
    PersonalPhoneNumber: "+1 (555) 369-2580",
    PersonalEmailAddress: "alice.brown@example.com",
    MarketingEmailID: "alice.brown.marketing@careervest.com",
    MarketingEmailPassword: "passwordabc",
    AssignedRecruiterID: 3,
    VisaStatus: "US Citizen",
    LinkedInURL: "https://www.linkedin.com/in/alicebrown",
    MarketingEndDate: "2023-05-01",
    JobOutcome: "Backed Out",
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_alice_brown.pdf",
    ClientStatus: "Inactive",
    CreatedTS: "2023-04-01T08:45:00Z",
    UpdatedTS: "2023-05-01T10:00:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Recruiter",
    SubscriptionPlanID: 2,
    PostPlacementPlanID: null,
    TotalDue: 2500,
    TotalPaid: 2500,
  },
  {
    ClientID: 5,
    ClientName: "Charlie Davis",
    EnrollmentDate: "2023-05-01",
    TechStack: "Vue.js, Node.js",
    MarketingStartDate: "2023-05-15",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 147-2589",
    PersonalEmailAddress: "charlie.davis@example.com",
    MarketingEmailID: "charlie.davis.marketing@careervest.com",
    MarketingEmailPassword: "passworddef",
    AssignedRecruiterID: 2,
    VisaStatus: "H1B",
    LinkedInURL: "https://www.linkedin.com/in/charliedavis",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_charlie_davis.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-05-01T14:00:00Z",
    UpdatedTS: "2023-05-15T09:30:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 1,
    PostPlacementPlanID: null,
    TotalDue: 5000,
    TotalPaid: 1000,
  },
  {
    ClientID: 6,
    ClientName: "Eva Wilson",
    EnrollmentDate: "2023-06-01",
    TechStack: "React Native, Firebase",
    MarketingStartDate: "2023-06-15",
    PlacedDate: "2023-07-15",
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 753-9514",
    PersonalEmailAddress: "eva.wilson@example.com",
    MarketingEmailID: "eva.wilson.marketing@careervest.com",
    MarketingEmailPassword: "passwordghi",
    AssignedRecruiterID: 3,
    VisaStatus: "US Citizen",
    LinkedInURL: "https://www.linkedin.com/in/evawilson",
    MarketingEndDate: "2023-07-15",
    JobOutcome: "Placed",
    JobStartDate: "2023-08-01",
    JobSalary: 105000,
    PercentageFee: 15,
    ResumeBlobKey: "resume_eva_wilson.pdf",
    ClientStatus: "Placed",
    CreatedTS: "2023-06-01T10:30:00Z",
    UpdatedTS: "2023-07-15T15:45:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Recruiter",
    SubscriptionPlanID: 2,
    PostPlacementPlanID: 1,
    TotalDue: 7500,
    TotalPaid: 5000,
  },
  {
    ClientID: 7,
    ClientName: "Frank Miller",
    EnrollmentDate: "2023-07-01",
    TechStack: "Ruby on Rails, PostgreSQL",
    MarketingStartDate: "2023-07-15",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 852-9630",
    PersonalEmailAddress: "frank.miller@example.com",
    MarketingEmailID: "frank.miller.marketing@careervest.com",
    MarketingEmailPassword: "passwordjkl",
    AssignedRecruiterID: 1,
    VisaStatus: "Green Card",
    LinkedInURL: "https://www.linkedin.com/in/frankmiller",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_frank_miller.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-07-01T09:15:00Z",
    UpdatedTS: "2023-07-15T11:00:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 1,
    PostPlacementPlanID: null,
    TotalDue: 5000,
    TotalPaid: 2500,
  },
  {
    ClientID: 8,
    ClientName: "Grace Lee",
    EnrollmentDate: "2023-08-01",
    TechStack: "Python, Flask, MongoDB",
    MarketingStartDate: "2023-08-15",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 741-8520",
    PersonalEmailAddress: "grace.lee@example.com",
    MarketingEmailID: "grace.lee.marketing@careervest.com",
    MarketingEmailPassword: "passwordmno",
    AssignedRecruiterID: 2,
    VisaStatus: "H1B",
    LinkedInURL: "https://www.linkedin.com/in/gracelee",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_grace_lee.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-08-01T13:45:00Z",
    UpdatedTS: "2023-08-15T10:30:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 2,
    PostPlacementPlanID: null,
    TotalDue: 7500,
    TotalPaid: 2500,
  },
  {
    ClientID: 9,
    ClientName: "Henry Taylor",
    EnrollmentDate: "2023-09-01",
    TechStack: "C#, ASP.NET Core",
    MarketingStartDate: "2023-09-15",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 963-7410",
    PersonalEmailAddress: "henry.taylor@example.com",
    MarketingEmailID: "henry.taylor.marketing@careervest.com",
    MarketingEmailPassword: "passwordpqr",
    AssignedRecruiterID: 3,
    VisaStatus: "US Citizen",
    LinkedInURL: "https://www.linkedin.com/in/henrytaylor",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_henry_taylor.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-09-01T11:00:00Z",
    UpdatedTS: "2023-09-15T14:15:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 1,
    PostPlacementPlanID: null,
    TotalDue: 5000,
    TotalPaid: 1000,
  },
  {
    ClientID: 10,
    ClientName: "Ivy Chen",
    EnrollmentDate: "2023-10-01",
    TechStack: "Java, Spring Boot, MySQL",
    MarketingStartDate: "2023-10-15",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 159-7532",
    PersonalEmailAddress: "ivy.chen@example.com",
    MarketingEmailID: "ivy.chen.marketing@careervest.com",
    MarketingEmailPassword: "passwordstu",
    AssignedRecruiterID: 1,
    VisaStatus: "F1 OPT",
    LinkedInURL: "https://www.linkedin.com/in/ivychen",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_ivy_chen.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-10-01T09:30:00Z",
    UpdatedTS: "2023-10-15T11:45:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 2,
    PostPlacementPlanID: null,
    TotalDue: 7500,
    TotalPaid: 2500,
  },
  {
    ClientID: 11,
    ClientName: "Jack Robinson",
    EnrollmentDate: "2023-11-01",
    TechStack: "Golang, Docker",
    MarketingStartDate: "2023-11-15",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 951-7532",
    PersonalEmailAddress: "jack.robinson@example.com",
    MarketingEmailID: "jack.robinson.marketing@careervest.com",
    MarketingEmailPassword: "passwordvwx",
    AssignedRecruiterID: 2,
    VisaStatus: "US Citizen",
    LinkedInURL: "https://www.linkedin.com/in/jackrobinson",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_jack_robinson.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-11-01T08:45:00Z",
    UpdatedTS: "2023-11-15T10:30:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 1,
    PostPlacementPlanID: null,
    TotalDue: 5000,
    TotalPaid: 1000,
  },
  {
    ClientID: 12,
    ClientName: "Lucy Wang",
    EnrollmentDate: "2023-12-01",
    TechStack: "Scala, Akka",
    MarketingStartDate: "2023-12-15",
    PlacedDate: null,
    BackedOutDate: null,
    BackedOutReason: null,
    PersonalPhoneNumber: "+1 (555) 753-9514",
    PersonalEmailAddress: "lucy.wang@example.com",
    MarketingEmailID: "lucy.wang.marketing@careervest.com",
    MarketingEmailPassword: "passwordyz1",
    AssignedRecruiterID: 3,
    VisaStatus: "H1B",
    LinkedInURL: "https://www.linkedin.com/in/lucywang",
    MarketingEndDate: null,
    JobOutcome: null,
    JobStartDate: null,
    JobSalary: null,
    PercentageFee: null,
    ResumeBlobKey: "resume_lucy_wang.pdf",
    ClientStatus: "Active",
    CreatedTS: "2023-12-01T11:15:00Z",
    UpdatedTS: "2023-12-15T14:00:00Z",
    CreatedBy: "Admin",
    UpdatedBy: "Admin",
    SubscriptionPlanID: 2,
    PostPlacementPlanID: null,
    TotalDue: 7500,
    TotalPaid: 2500,
  },
]

export const dummyRecruiters: Employee[] = [
  {
    EmployeeID: 1,
    FirstName: "Sarah",
    LastName: "Johnson",
    PersonalEmailAddress: "sarah.johnson@example.com",
    CompanyEmailAddress: "sarah.johnson@careervest.com",
    Role: "Recruiter",
  },
  {
    EmployeeID: 2,
    FirstName: "Michael",
    LastName: "Brown",
    PersonalEmailAddress: "michael.brown@example.com",
    CompanyEmailAddress: "michael.brown@careervest.com",
    Role: "Recruiter",
  },
  {
    EmployeeID: 3,
    FirstName: "Emily",
    LastName: "Davis",
    PersonalEmailAddress: "emily.davis@example.com",
    CompanyEmailAddress: "emily.davis@careervest.com",
    Role: "Recruiter",
  },
]

export const dummySubscriptionPlans: SubscriptionPlan[] = [
  { SubscriptionPlanID: 1, PlanName: "Basic", Description: "Basic subscription plan", TotalSubscriptionAmount: 5000 },
  {
    SubscriptionPlanID: 2,
    PlanName: "Premium",
    Description: "Premium subscription plan",
    TotalSubscriptionAmount: 7500,
  },
]

export const dummyPostPlacementPlans: PostPlacementPlan[] = [
  {
    PostPlacementPlanID: 1,
    PlanName: "Standard",
    Description: "Standard post-placement plan",
    TotalPostPlacementAmount: 2500,
  },
  {
    PostPlacementPlanID: 2,
    PlanName: "Extended",
    Description: "Extended post-placement plan",
    TotalPostPlacementAmount: 5000,
  },
]

