import type { Employee } from "../types/employee"

export const dummyEmployees: Employee[] = [
  {
    EmployeeID: 1,
    FirstName: "John",
    LastName: "Doe",
    PersonalEmailAddress: "john.doe@example.com",
    CompanyEmailAddress: "john.doe@company.com",
    Role: "Software Developer",
    HireDate: "2023-01-15",
    TerminationDate: null,
    Status: "Active",
    Department: "Engineering",
    Position: "Senior Developer",
    Manager: "Jane Smith",
    Salary: 85000,
    PhoneNumber: "+1 (555) 123-4567",
    Address: "123 Main St, Anytown, USA",
    EmergencyContact: "Jane Doe",
    EmergencyContactPhone: "+1 (555) 987-6543",
  },
  {
    EmployeeID: 2,
    FirstName: "Jane",
    LastName: "Smith",
    PersonalEmailAddress: "jane.smith@example.com",
    CompanyEmailAddress: "jane.smith@company.com",
    Role: "Project Manager",
    HireDate: "2022-05-01",
    TerminationDate: null,
    Status: "Active",
    Department: "Project Management",
    Position: "Senior Project Manager",
    Manager: "Mike Johnson",
    Salary: 95000,
    PhoneNumber: "+1 (555) 234-5678",
    Address: "456 Oak St, Othertown, USA",
    EmergencyContact: "John Smith",
    EmergencyContactPhone: "+1 (555) 876-5432",
  },
  {
    EmployeeID: 3,
    FirstName: "Mike",
    LastName: "Johnson",
    PersonalEmailAddress: "mike.johnson@example.com",
    CompanyEmailAddress: "mike.johnson@company.com",
    Role: "HR Manager",
    HireDate: "2021-09-15",
    TerminationDate: null,
    Status: "Active",
    Department: "Human Resources",
    Position: "HR Manager",
    Manager: "Sarah Williams",
    Salary: 90000,
    PhoneNumber: "+1 (555) 345-6789",
    Address: "789 Pine St, Somewhere, USA",
    EmergencyContact: "Emily Johnson",
    EmergencyContactPhone: "+1 (555) 765-4321",
  },
]

